import React, { useContext } from "react";
import { useSession } from "next-auth/react";

import { AppContext } from "../contexts/AppContext";
import { SinglePost } from "@/components/SimplePost";
import { Login } from "@/components/Login";
import { Modal } from "@/components/Modal";

import Head from "next/head";
import { LeftSide } from "@/components/LeftSide";
import { Trending } from "@/components/Trending";

const PostPage = () => {
  const { data: session } = useSession();
  const [appContext] = useContext(AppContext);

  if (!session) return <Login />;

  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative max-w-[1400px] mx-auto">
        <LeftSide />
        <div className="flex gap-6">
          <SinglePost />
          <Trending />
          {appContext?.isModalOpen && <Modal />}
        </div>
      </main>
    </div>
  );
};

export default PostPage;
