import Head from "next/head";
import { useSession } from "next-auth/react";
import { LeftSide } from "@/components/LeftSide";
import { Feed } from "@/components/Feed";
import { Login } from "@/components/Login";
import { AppContext } from "@/contexts/AppContext";
import { useContext } from "react";
import { Modal } from "@/components/Modal";
import { Trending } from "@/components/Trending";

export default function Home() {
  const { data: session } = useSession();
  const [appContext] = useContext(AppContext);

  if (!session) return <Login />;

  return (
    <>
      <Head>
        <title className="t-white">Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          http-equiv="Content-Security-Policy"
          content="upgrade-insecure-requests"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative max-w-[1400px] mx-auto">
        <LeftSide />
        <div className="flex gap-6">
          <Feed />
          <Trending />

          {appContext?.isModalOpen && <Modal />}
        </div>
      </main>
    </>
  );
}
