import Head from "next/head";
import { LeftSide } from "@/components/LeftSide";
import { useSession } from "next-auth/react";
import { Login } from "@/components";

export default function Home() {
  const { data: session } = useSession();

  if (!session) return <Login />;

  return (
    <>
      <Head>
        <title className="t-white">Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative max-w-[1400px] mx-auto">
        <LeftSide />
      </main>
    </>
  );
}
